name: TFPlan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # sunday at 00:00
    - cron: "0 0 * * 0"


jobs:
  tfplan:
    # required for google-github-actions/auth
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: terraform-linters/setup-tflint@v4
    - run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: "Authenticate to GCP for terraform commands"
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        # do we need this for cloud run domain mappings?
        export_environment_variables: true

    - run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -detailed-exitcode
      env:
        # manual token with repo rights
        GITHUB_TOKEN: ${{ secrets.PAT }}
